version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github_actions

  django:
    container_name: django
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    entrypoint: sh -c "poetry run python manage.py migrate && poetry run python manage.py runserve 0.0.0.0:8000"
    environment:
      - SECRET_KEY=django-insecure-hwd0q$q^d9uaxfgai!(y=$1_fv&69^4ox!^!fq=h%h$o=8mpz4
      - GITHUB_WORKFLOW=True
      - DEBUG=True
    volumes:
      - .:/app
    expose:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure