name: CI

on:
  push:
    branches: [ "develop"]

  pull_request:
    branches: [ "develop", "main" ]

jobs:
  django-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker
        run: docker compose -f local.docker-compose.yml build

      - name: Run isort
        run: docker compose -f local.docker-compose.yml run django poetry run isort euss_ya_apps/ --check

      - name: Run black
        run: docker compose -f local.docker-compose.yml run django poetry run black euss_ya_apps/ --check

      - name: Run flake8
        run: docker compose -f local.docker-compose.yml run django poetry run flake8

      - name: Run mypy
        run: docker compose -f local.docker-compose.yml run django poetry run mypy --config mypy.ini euss_ya_apps/

      - name: Run tests
        run: docker compose -f local.docker-compose.yml run django poetry run py.test